Add proper validation for empty batch in External Source
Previous error:
```
Error when executing Mixed operator MakeContiguous encountered:
[/home/klecki/work/salvador/dali/dali/pipeline/data/tensor_list.cc:519] Assert on "IsValidType(new_type)" failed: TensorList cannot be resized with invalid type. To zero out the TensorList Reset() can be used.
```

New error:
```
RuntimeError: [/home/klecki/work/salvador/dali/dali/pipeline/operator/builtin/external_source.h:496] Assert on "batch.num_samples() > 0" failed: ExternalSource expects non-empty batches to be provided as
the input. Got batch with 0 samples.
```

Signed-off-by: Krzysztof Lecki <klecki@nvidia.com>